NERSC's HPSS has binaries in new locations
WIPACrepo/lta pull request #196
Opened 2021-04-19 20:11 UTC by jnbellinger

2021-04-21 20:31 UTC, blinkdog requested changes
The path changes for the NERSC binaries looks good.

Plumbing them through configuration may allow more flexibility for the future, but that's more complicated and higher touch, so no need to do it now. If NERSC changes up the paths again before 2022, we should consider it though.

LGTM will complain about the import change, so if we can fix those up, I think this one is ready to merge.

2021-04-21 20:31 UTC, blinkdog commented on lta/nersc_mover.py
> +from logging import Logger
Our integration with LGTM doesn't like that we use `from X import Y` and `import X`.
Could you remove this import and restore `Logger = logging.Logger` below?

2021-04-21 20:31 UTC, blinkdog commented on lta/nersc_mover.py
> -Logger = logging.Logger
This is the `Logger = logging.Logger` that I was talking about.

2021-04-21 20:31 UTC, blinkdog commented on lta/nersc_retriever.py
> +from logging import Logger
Same thing here, need to fix it for LGTM.

2021-04-21 20:31 UTC, blinkdog commented on lta/nersc_verifier.py
> +from logging import Logger
Same thing here, need to fix it for LGTM.

2021-04-22 01:56 UTC, blinkdog requested changes
Looks like the path for `hsi` is incorrect.

```
[pmeade@dtn01 ~]$ ls /usr/bin/hsi
ls: cannot access /usr/bin/hsi: No such file or directory
[pmeade@dtn01 ~]$ ls /usr/local/bin/hsi
/usr/local/bin/hsi
```

2021-04-22 02:57 UTC, jnbellinger commented
icecubed@cori08:~/NEWLTA/lta> which hsi
/usr/bin/hsi

It's very odd that dtn systems should be different, but these scripts run on the cori systems

2021-04-23 06:13 UTC, blinkdog commented
> icecubed@cori08:~/NEWLTA/lta> which hsi
> /usr/bin/hsi
> 
> It's very odd that dtn systems should be different, but these scripts run on the cori systems

Wow, that is surprising! Never mind then, carry on with `/usr/bin/hsi` :smile:

2021-04-28 05:14 UTC, blinkdog commented
@jnbellinger If you fix the LGTM issues with the `import` and `import from`, this one is ready to merge.

2021-05-03 17:21 UTC, merged